# Generated by Django 3.2.3 on 2021-05-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username của người dùng', max_length=200)),
                ('password', models.CharField(help_text='Password của người dùng', max_length=50)),
                ('name', models.CharField(help_text='Tên người dùng', max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(choices=[('1', 'Nữ'), ('0', 'Nam')], default=1, max_length=1)),
                ('phone', models.CharField(help_text='Số điện thoại', max_length=11)),
                ('addr', models.CharField(help_text='Địa chỉ', max_length=200)),
            ],
        ),
    ]
