# Generated by Django 3.2.3 on 2021-05-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('1', 'Drink'), ('2', 'Food'), ('3', 'Album'), ('4', 'Lightstick')], max_length=200, null=True),
        ),
    ]
