# Generated by Django 3.2.3 on 2021-05-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210529_2314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
